services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - ./dev.env

  django:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./${ENV}.env
    depends_on:
      - postgres
    networks:
      - donate-network

networks:
  donate-network:
    driver: bridge