services:
  postgres:
    image: postgis/postgis:14-3.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql
    env_file:
      - ./dev.env
    networks:
      - donate-network

  django:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./${ENV}.env
    depends_on:
      - postgres
    networks:
      - donate-network

networks:
  donate-network:
    driver: bridge